id: A8E7E48E9
title: A Liturgy for the Activity Manual of the Blazing Wrathful Guru, Hayagrīva and
  Garuḍa
type: translation
pechas:
- I497B91B4
- I606187BC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:01:56.458401
  last_modified_at: 2023-01-04 12:01:56.458405
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I497B91B4/5834: 2C23
  I606187BC/5AEA: 2C23
